@startuml
class ConfigManager {
    - filename: string
    - configValue: map<string, string>
    + ConfigManager()
    + ConfigManager(const string&)
    + ConfigManager(const ConfigManager&)
    + loadConfig(): bool
    + saveConfig(): bool
    + getValue(const string&) const string
    + setValue(const string&, const string&)
}
@enduml