@startuml
class ConfigManager {
    - filename: string
    - configValue: map<string, string>
    + ConfigManager()
    + ConfigManager(filename: const string&)
    + ConfigManager(copyConfigManager: const ConfigManager&)
    + loadConfig(): bool
    + saveConfig(): bool
    + getValue(key: const string&) const: string
    + setValue(key: const string&, value: const string&)
}
@enduml