@startuml
class Data {
    - day: int
    - month: int
    - year: int
    + Data()
    + Data(int, int, int)
    + getDay(): int
    + getMonth(): int
    + getYear(): int
    + toString(): string
}

@enduml
